name: Unity Build CI

on:
  push:
    branches:
      - main  # Monitor the main branch for new commits

jobs:
  acquire_ulf:
    name: Acquire .ulf file 🔑
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'

      - name: Install node package, `unity-license-activate`
        run: npm install --global unity-license-activate

      - name: Activate the license
        run: unity-license-activate "${{ secrets.UNITY_EMAIL }}" "${{ secrets.UNITY_PASSWORD }}" "${{ needs.request_alf.outputs.alf }}"

      - name: Read ulf
        id: ulfRead
        uses: juliangruber/read-file-action@v1.1.4
        with:
          path: ${{ env.ULF_FILE }}

      - name: Update secret UNITY_LICENSE
        uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'UNITY_LICENSE'
          value: '${{ steps.ulfRead.outputs.content }}'
          token: ${{ secrets.ACCESS_TOKEN }}

  build:
    runs-on: windows-latest  # Runner; adjust for your needs (e.g., windows-latest)

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set up Unity
      uses: game-ci/unity-builder@v2
      with:
        unityVersion: 6000.0.25f1  # Match your Unity version
        targetPlatform: StandaloneWindows64  # Build target platform

    - name: Build the Project
      uses: game-ci/unity-builder@v2
      with:
        projectPath: .  # Adjust if your Unity project is in a subfolder
        targetPlatform: StandaloneWindows64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: build/StandaloneWindows64/  # Path to your executable
